language: python

python:
  - 3.4
  - 3.5

sudo: false
addons:
  apt:
    packages:
      - samtools

install:
  - pip install -r requirements.txt
  - pip install -U pytest pytest-cov coverage codecov sphinx
  - python setup.py install

before_script:
  - cd tests

script:
  - py.test --cov=./
#  - python test_Baminfo.py
#  - python test_bamTobigwig.py
#  - python test_regioncount.py

after_success:
  - bash <(curl -s https://codecov.io/bash)