language: python

python:
  - 3.4
  - 3.5

sudo: false
addons:
  apt:
    packages:
      - samtools

install:
  - pip install -r requirements.txt

before_script:
  - cd tests

script:
  python test_Baminfo.py
  python test_bamTobigwig.py
  python test_regioncount.py